import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import localFont from "next/font/local";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const myFont = localFont({
  src: "./versatylorounded.ttf",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Commune Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased bg-main-bg flex !relative flex-col items-center overflow-x-hidden md:bg-gradient-to-t from-fuchsia-400 to-cyan-500",
          myFont.className
        )}
      >
        <Suspense>
          <div className="md:max-w-md w-full bg-main-bg relative">
            {children}
            <ToastContainer />
          </div>
        </Suspense>
      </body>
    </html>
  );
}
